### PR TITLE
Added CSS only version

### PR DESCRIPTION
**Pull request by arguiot**
I added a CSS version of Lunar Icons using the `content` modifier.

### CODE REVIEW

**Comment by lucasgruwez** [comment]
Hey just before I merge your PR, do you mind commenting in this thread a quick documentation of how the CSS only version should be used?

I like the implementation though! Really neat!

**Comment by arguiot** [comment]
Well, there is nothing to say... you just add 
```html
<link rel="stylesheet" href="./path/to/lunar-icons.min.css">
```
and you're done.

**Comment by arguiot** [comment]
Currently, the CSS file is quite big, but I'll try to make Lunar Icons into a font, and make it super tiny

**Comment by arguiot** [comment]
Ok, so I made lunar icons into a font, but for some reasons, the glyphs are looking very weird

**Pull request closed without merging**
